---
permalink: migrate/migrate-to-latest-ontaptools.html 
sidebar: sidebar 
keywords: migrate 
summary: 스토리지 데이터를 마이그레이션할 때 REST API를 사용하여 스토리지 백엔드를 수동으로 온보드합니다. VASA Provider 데이터를 마이그레이션할 때 기존 Derby 데이터베이스에서 데이터를 내보내고 MongoDB 데이터베이스로 가져옵니다. 
---
= VMware vSphere 9.x용 ONTAP 툴에서 10.3로 마이그레이션합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 데이터를 마이그레이션할 때 REST API를 사용하여 스토리지 백엔드를 수동으로 온보드합니다. VASA Provider 데이터를 마이그레이션할 때 기존 Derby 데이터베이스에서 데이터를 내보내고 MongoDB 데이터베이스로 가져옵니다.


NOTE: 설정 시 VASA Provider 기능만 제공하는 경우에만 VMware vSphere 9.xx 설정용 ONTAP 툴을 마이그레이션해야 합니다.


NOTE: ONTAP 툴 10.3은 VMFS 데이터 저장소를 사용하는 NVMe-oF만 지원하므로 VMware vSphere 9.x용 ONTAP 툴에서 10.3으로 마이그레이션한 후 NVMe/FC 프로토콜을 사용하는 VVOL 데이터 저장소가 작동하지 않습니다.

* 이 작업에 대한 정보 *

VMware vSphere 9.12D1 및 9.13D2 릴리즈용 ONTAP 툴에서 10.3으로 마이그레이션할 수 있습니다.


NOTE: 패치 릴리스로 업그레이드하기 전에 현재 릴리스에서 OVA 백업을 가져와야 합니다.



== 일반적인 마이그레이션 단계

. VMware vSphere 10.3 릴리스용 ONTAP용 OVA 도구를 배포합니다.
. VMware vSphere 10.3 릴리즈용 ONTAP 툴로 마이그레이션할 vCenter Server 인스턴스를 추가합니다. link:../configure/add-vcenter.html["vCenter Server 인스턴스를 추가합니다"]을 참조하십시오.
. VMware vSphere 플러그인 vCenter Server API용 ONTAP 툴에서 로컬로 스토리지 백엔드를 온보드합니다. 마이그레이션을 위해 스토리지를 로컬 범위 스토리지로 추가합니다.
. VMware vSphere 9.xx용 ONTAP 툴에서 마이그레이션된 NFS 및 VMFS 데이터 저장소는 데이터 저장소 검색 작업이 트리거된 후에만 VMware vSphere 10.3용 ONTAP 툴에 표시됩니다. 이 작업은 트리거하는 데 최대 30분이 걸릴 수 있습니다. 데이터 저장소가 VMware vSphere Plugin 사용자 인터페이스용 ONTAP Tools 페이지의 개요 페이지에 표시되는지 확인합니다.




== SRA 마이그레이션 단계

* 시작하기 전에 *

마이그레이션하기 전에 사이트 중 하나가 보호 상태이고 다른 사이트가 복구 상태에 있는지 확인합니다.


NOTE: 페일오버가 방금 완료되었고 재보호가 보류 중인 경우에는 마이그레이션하지 마십시오. 재보호를 완료한 다음 마이그레이션을 수행합니다. 복구 계획 테스트를 완료한 후 테스트 복구를 정리하고 마이그레이션을 시작합니다.

. VMware Live Site Recovery 사용자 인터페이스에서 VMware vSphere 9.xx 릴리즈 SRA 어댑터용 ONTAP 툴을 삭제하려면 다음 단계를 수행하십시오.
+
.. VMware Live Site Recovery 구성 관리 페이지로 이동합니다
.. 스토리지 복제 어댑터 * 섹션으로 이동합니다
.. 줄임표 메뉴를 선택하고 * Reset configuration * 을 선택합니다
.. 줄임표 메뉴를 선택하고 * 삭제 * 를 선택합니다
+
보호 사이트와 복구 사이트 모두에서 다음 단계를 수행합니다.



. 의 단계에 따라 보호 및 복구 사이트 모두에 VMware vSphere 10.3 SRA 어댑터용 ONTAP 툴을 설치합니다 link:../protect/configure-on-srm-appliance.html["VMware Live Site Recovery 어플라이언스에서 SRA를 구성합니다"]
. VMware Live Site Recovery 사용자 인터페이스 페이지에서 * 스토리지 검색 * 및 * 장치 검색 * 작업을 수행하고 마이그레이션 전의 상태로 장치가 표시되는지 확인합니다.




== VASA Provider 마이그레이션 단계

. VMware vSphere용 기존 ONTAP 툴에서 더비 포트 1527을 활성화합니다. 포트를 활성화하려면 루트 사용자로 CLI에 로그인하고 다음 명령을 실행합니다.
+
[listing]
----
iptables -I INPUT 1 -p tcp --dport 1527 -j ACCEPT
----
. VMware vSphere 10.3용 ONTAP 툴용 OVA 구축
. VMware vSphere 10.3 릴리즈용 ONTAP 툴로 마이그레이션할 vCenter Server 인스턴스를 추가합니다. 을 link:../configure/add-vcenter.html["vCenter Server 인스턴스를 추가합니다"]참조하십시오.
. 원격 플러그인 vCenter Server API에서 로컬로 스토리지 백엔드를 온보드합니다. 마이그레이션을 위해 스토리지를 로컬 범위로 추가합니다.
. 마이그레이션하려면 다음 API 호출을 실행합니다.
+
[]
====
*HTTP 메서드 및 끝점*

이 REST API 호출은 다음과 같은 메소드와 엔드포인트를 사용합니다.

|===


| * HTTP 메서드 * | * 경로 * 


| 게시 | /api/v1 을 참조하십시오 
|===
* 처리 유형 *

비동기식

* 컬링 예제 *

/api/v1/vCenters/{vcguid}/migration-jobs

* JSON 입력 예제 * 9.12 및 9.13에서 마이그레이션 요청 본문:

{"OTV_IP":"10.12.13.45","VASA_provider_credentials":{"username":"vasauser", "password":"***********"}"database_password":" ****************

다른 릴리스 마이그레이션에 대한 요청 본문:

{"OTV_IP":"10.12.13.45","VASA_provider_credentials":{"사용자 이름":"vasauser","암호":"**********"}

* JSON 출력 예 *

작업 객체가 반환됩니다. 다음 단계에서 사용할 작업 식별자를 저장해야 합니다.

{"id":123,"migration_id":"d50073ce-35b4-4c51-9d2e-4ce66f802c35","status":"running"}

====
. 다음 URI를 사용하여 상태를 확인합니다.
+
[listing]
----
https://xx.xx.xx.xxx:8443/virtualization/api/jobmanager/v2/jobs/<JobID>?includeSubJobsAndTasks=true
----
+
작업이 완료되면 마이그레이션 보고서를 검증합니다. 보고서는 작업 데이터의 일부이며 작업 응답에서 볼 수 있습니다.

. VMware vSphere 스토리지 공급자용 ONTAP 툴을 vCenter Server 및 에 추가합니다 link:../configure/registration-process.html["vCenter Server 인스턴스에 VASA Provider를 등록합니다"].
. 유지 관리 콘솔에서 VMware vSphere 스토리지 공급자용 ONTAP 툴 9.10/9.11/9.12/9.13 VASA Provider 서비스를 중지합니다.
+
VASA Provider를 삭제하지 마십시오.

+
이전 VASA Provider가 중지되면 vCenter Server가 VMware vSphere용 ONTAP 툴로 페일오버됩니다. 모든 데이터 저장소와 VM에 액세스할 수 있으며 VMware vSphere용 ONTAP 툴을 통해 제공됩니다.

. 다음 API를 사용하여 패치 마이그레이션을 수행합니다.
+
[]
====
*HTTP 메서드 및 끝점*

이 REST API 호출은 다음과 같은 메소드와 엔드포인트를 사용합니다.

|===


| * HTTP 메서드 * | * 경로 * 


| 패치 | /api/v1 을 참조하십시오 
|===
* 처리 유형 *

비동기식

* 컬링 예제 *

패치 "/api/v1/vCenters/56d373bd-4163-44f9-a872-9adabb008ca9/migration-jobs/84dr73bd-9173-65r7-w345-8ufdb887d43

* JSON 입력 예 *

{"id":123,"migration_id":"d50073ce-35b4-4c51-9d2e-4ce66f802c35","status":"running"}

* JSON 출력 예 *

작업 객체가 반환됩니다. 다음 단계에서 사용할 작업 식별자를 저장해야 합니다.

{"id":123,"migration_id":"d50073ce-35b4-4c51-9d2e-4ce66f802c35","status":"running"}

패치 작업을 위한 요청 본문이 비어 있습니다.


NOTE: UUID는 사후 마이그레이션 API의 응답으로 반환된 마이그레이션 uuid입니다.

패치 마이그레이션 API가 성공적으로 실행되면 모든 VM이 스토리지 정책을 준수합니다.

====
+
마이그레이션에 성공하고 ONTAP Tools 10.3을 vCenter Server에 등록한 후 다음을 수행합니다.

+
** 모든 호스트에서 인증서를 새로 고칩니다.
** 잠시 기다린 후 데이터 저장소(DS) 및 가상 머신(VM) 작업을 수행합니다. 대기 시간은 설정에 있는 호스트, DS 및 VM의 수에 따라 다릅니다. 기다리지 않으면 작업이 간헐적으로 실패할 수 있습니다.




* 완료 후 *

업그레이드 후 가상 머신 규정 준수 상태가 최신이 아니면 다음 단계를 사용하여 가상 머신 스토리지 정책을 다시 적용합니다.

. 데이터 저장소로 이동하고 * Summary * > * VM Storage policies * 를 선택합니다.
+
VM 스토리지 정책 준수 * 에서 규정 준수 상태를 확인할 수 있습니다. 업데이트 안됨 * 으로 표시됩니다

. 스토리지 VM 정책과 해당 VM을 선택합니다
. 적용 * 을 선택합니다
+
VM 저장소 정책 준수 * 의 규정 준수 상태가 이제 준수 상태로 표시됩니다.



* 관련 정보 *

link:../upgrade/upgrade-ontap-tools.html["VMware vSphere 10.x용 ONTAP 툴을 10.3로 업그레이드하십시오"]
