---
permalink: deploy/ontap-tools-deployment.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 어플라이언스용 ONTAP 툴은 NFS 및 VMFS 데이터 저장소를 지원하는 핵심 서비스를 갖춘 소규모 단일 노드로 구축됩니다. 
---
= VMware vSphere용 ONTAP 툴을 구축합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 어플라이언스용 ONTAP 툴은 NFS 및 VMFS 데이터 저장소를 지원하는 핵심 서비스를 갖춘 소규모 단일 노드로 구축됩니다.

* 시작하기 전에 *

VMware의 컨텐츠 라이브러리는 VM 템플릿, vApp 템플릿 및 기타 유형의 파일을 저장하는 컨테이너 객체입니다. 콘텐츠 라이브러리를 사용한 배포는 네트워크 연결에 의존하지 않으므로 원활한 환경을 제공합니다.


NOTE: 클러스터 내의 모든 호스트가 액세스할 수 있도록 컨텐츠 라이브러리를 공유 데이터 저장소에 저장해야 합니다. 어플라이언스를 HA 구성으로 구성하기 전에 OVA를 저장할 컨텐츠 라이브러리를 생성합니다. 배포 후에는 콘텐츠 라이브러리 서식 파일을 삭제하지 마십시오.


NOTE: 나중에 HA 배포를 활성화하려면 ONTAP 툴을 호스팅하는 가상 시스템을 ESXi 호스트에 직접 배포하지 마십시오. 대신 클러스터 또는 리소스 풀에 배포합니다.

콘텐츠 라이브러리가 없는 경우 다음 단계를 따라 콘텐츠 라이브러리를 만듭니다.

* 콘텐츠 라이브러리 만들기 * 소규모 단일 노드 배포만 사용할 계획이라면 콘텐츠 라이브러리를 만들 필요가 없습니다.

.  `.zip`에서 VMware vSphere용 ONTAP 툴에 대한 바이너리(_.ova_)와 서명된 인증서가 포함된 파일을 https://mysupport.netapp.com/site/products/all/details/otv10/downloads-tab["NetApp Support 사이트"^] 다운로드합니다.
. vSphere Client에 로그인합니다
. vSphere Client 메뉴를 선택하고 * Content libraries * 를 선택합니다.
. 페이지 오른쪽에서 * 만들기 * 를 선택합니다.
. 라이브러리 이름을 지정하고 콘텐츠 라이브러리를 만듭니다.
. 만든 콘텐츠 라이브러리로 이동합니다.
. 페이지 오른쪽의 * Actions * 를 선택하고 * Import item * 을 선택한 후 OVA 파일을 가져옵니다.



NOTE: 자세한 내용은 https://blogs.vmware.com/vsphere/2020/01/creating-and-using-content-library.html["콘텐츠 라이브러리 만들기 및 사용"] 블로그 를 참조하십시오.


NOTE: 구축을 진행하기 전에 인벤토리에 있는 클러스터의 DRS(Distributed Resource Scheduler)를 '보존적'으로 설정합니다. 이렇게 하면 설치 중에 VM이 마이그레이션되지 않습니다.

VMware vSphere용 ONTAP 툴은 처음에 비 HA 설정으로 구축됩니다. HA 배포로 확장하려면 CPU 핫 플러그 및 메모리 핫 플러그인을 활성화해야 합니다. 배포 프로세스의 일부로 이 단계를 수행하거나 배포 후 VM 설정을 편집할 수 있습니다.

.단계
.  `.zip`에서 VMware vSphere용 ONTAP 툴에 대한 바이너리(_.ova_)와 서명된 인증서가 포함된 파일을 https://mysupport.netapp.com/site/products/all/details/otv10/downloads-tab["NetApp Support 사이트"^] 다운로드합니다. 콘텐츠 라이브러리로 OVA를 가져온 경우 이 단계를 건너뛰고 다음 단계를 진행할 수 있습니다.
. vSphere 서버에 로그인합니다.
. OVA를 구축할 리소스 풀, 클러스터 또는 호스트로 이동합니다.
+

NOTE: VMware vSphere 가상 머신용 ONTAP 툴을 관리하는 VVOL 데이터 저장소에 저장하지 마십시오.

. 콘텐츠 라이브러리 또는 로컬 시스템에서 OVA를 배포할 수 있습니다.
+
|===


| 로컬 시스템에서 | 콘텐츠 라이브러리에서 


| a. 마우스 오른쪽 단추를 클릭하고 * Deploy OVF template... *.b. URL에서 OVA 파일을 선택하거나 해당 위치를 찾은 후 * Next * 를 선택합니다. | a. 콘텐츠 라이브러리로 이동하여 배포할 라이브러리 항목을 선택합니다. b. * Actions * > * 이 템플릿에서 New VM * 을 선택합니다 
|===
. Select a name and folder * 필드에 가상 머신 이름을 입력하고 위치를 선택합니다.
+
** vCenter Server 8.0.3 버전을 사용하는 경우 * 이 가상 시스템의 하드웨어 사용자 정의 * 옵션을 선택합니다. 그러면 * 완료 준비 * 창으로 진행하기 전에 * 하드웨어 사용자 정의 * 라는 추가 단계가 활성화됩니다.
** vCenter Server 7.0.3 버전을 사용 중인 경우 구축 종료 시 * 다음 단계는 무엇입니까? * 섹션의 단계를 따르십시오.


. 컴퓨터 리소스를 선택하고 * 다음 * 을 선택합니다. 필요에 따라 배포된 VM의 전원을 자동으로 켜려면 * 확인란을 선택합니다.
. 템플릿의 세부 정보를 검토하고 * 다음 * 을 선택합니다.
. 사용권 계약을 읽고 동의한 후 * Next * 를 선택합니다.
. 구성 및 디스크 형식에 대한 스토리지를 선택하고 * Next * 를 선택합니다.
. 각 소스 네트워크에 대한 대상 네트워크를 선택하고 * 다음 * 을 선택합니다.
. Customize template * 창에서 필수 필드를 입력하고 * Next * 를 선택합니다.
+
** 이 정보는 설치 중에 검증됩니다. 일치하지 않는 경우 웹 콘솔에 오류 메시지가 나타나고 수정하라는 메시지가 표시됩니다.
** 호스트 이름은 문자(A-Z, a-z), 숫자(0-9) 및 하이픈(-)을 포함해야 합니다. 이중 스택을 구성하려면 IPv6 주소에 매핑된 호스트 이름을 지정합니다.
+

NOTE: Pure IPv6는 지원되지 않습니다. 혼합 모드는 IPv6 및 IPv4 주소를 모두 포함하는 VLAN에서 지원됩니다.



. vCenter Server 8.0.3 버전을 사용하는 경우 * Customize hardware * 창에서 * CPU hot add * 및 * Memory hot plug * 옵션을 활성화하여 HA 기능을 허용합니다.
. 완료 준비 * 창에서 세부 정보를 검토하고 * 마침 * 을 선택합니다.
+
구축 작업이 생성되면 vSphere 작업 표시줄에 진행 상황이 표시됩니다.

. 작업 완료 후 VM의 전원을 켭니다.


VM의 웹 콘솔에서 설치 진행률을 추적할 수 있습니다.

OVF 양식에 불일치가 있는 경우 대화 상자에 수정 조치가 표시됩니다. 탭 버튼을 사용하여 탐색하고 필요한 내용을 변경한 다음 "확인"을 선택합니다. 문제를 해결하기 위해 세 번 시도할 수 있습니다. 세 번 시도해도 문제가 계속되면 설치 프로세스가 중지되고 새 가상 컴퓨터에서 설치를 다시 시도하는 것이 좋습니다.

.다음 단계
vCenter Server 7.0.3과 함께 VMware vSphere용 ONTAP 툴을 배포한 경우 구축 후 다음 단계를 수행합니다.

. vCenter 클라이언트에 로그인합니다
. ONTAP 도구 노드의 전원을 끕니다.
. Inventory * 아래에서 VMware vSphere 가상 머신용 ONTAP 툴로 이동하고 * Edit settings * 옵션을 선택합니다.
. CPU * 옵션 아래에서 * Enable CPU hot add * 확인란을 선택합니다
. 메모리 * 옵션에서 * 메모리 핫 플러그 * 에 대해 * 활성화 * 확인란을 선택합니다.

