---
permalink: concepts/rbac-ontap-use.html 
sidebar: sidebar 
keywords: ontap rbac, use ontap rbac 
summary: VMware vSphere 10 RBAC를 운영 환경에서 사용하기 전에 ONTAP를 사용하여 구축하는 ONTAP 툴의 여러 측면을 고려해야 합니다. 
---
= VMware vSphere 10용 ONTAP 툴과 함께 ONTAP RBAC를 사용하십시오
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 10 RBAC를 운영 환경에서 사용하기 전에 ONTAP를 사용하여 구축하는 ONTAP 툴의 여러 측면을 고려해야 합니다.



== 구성 프로세스 개요

VMware vSphere 10용 ONTAP 툴에는 사용자 지정 역할을 가진 ONTAP 사용자를 생성할 수 있는 지원이 포함되어 있습니다. 이 정의는 ONTAP 클러스터에 업로드할 수 있는 JSON 파일로 패키지됩니다. 사용자를 생성하고 환경 및 보안 요구에 맞게 역할을 조정할 수 있습니다.

주요 구성 단계는 아래에 자세히 설명되어 있습니다. link:../configure/configure-user-role-and-privileges.html["ONTAP 사용자 역할 및 권한을 구성합니다"]자세한 내용은 을 참조하십시오.

.1. 준비
ONTAP 툴 관리자와 ONTAP 클러스터 모두에 대한 관리 자격 증명이 있어야 합니다.

.2. JSON 정의 파일을 다운로드합니다
ONTAP 도구 관리자 사용자 인터페이스에 로그인한 후 RBAC 정의가 포함된 JSON 파일을 다운로드할 수 있습니다.

.3. 역할이 있는 ONTAP 사용자를 생성합니다
System Manager에 로그인한 후 사용자 및 역할을 생성할 수 있습니다.

. 왼쪽에서 * Cluster * 를 선택한 다음 * Settings * 를 선택합니다.
. 아래로 스크롤하여 * 사용자 및 역할 * 을 클릭합니다 `-->`.
. 사용자 * 아래에서 * 추가 * 를 선택하고 * 가상화 제품 * 을 선택합니다.
. 로컬 워크스테이션에서 JSON 파일을 선택하고 업로드합니다.


.4. 역할을 구성합니다
역할을 정의하는 과정에서 몇 가지 관리 결정을 내려야 합니다. 자세한 내용은 을 <<System Manager를 사용하여 역할을 구성합니다>>참조하십시오.



== System Manager를 사용하여 역할을 구성합니다

System Manager로 새로운 사용자 및 역할을 생성하고 JSON 파일을 업로드한 후에는 환경과 요구에 따라 역할을 사용자 지정할 수 있습니다.



=== 핵심 사용자 및 역할 구성

RBAC 정의는 VSC, VASA Provider, SRA의 조합을 포함하여 여러 제품 기능으로 패키지됩니다. RBAC 지원이 필요한 환경 또는 환경을 선택해야 합니다. 예를 들어, 원격 플러그인 기능을 지원하는 역할이 필요한 경우 VSC를 선택합니다. 또한 사용자 이름과 관련 암호도 선택해야 합니다.



=== 권한

Privileges 역할은 ONTAP 스토리지에 필요한 액세스 수준에 따라 4세트로 구성됩니다. 역할의 기반이 되는 Privileges는 다음과 같습니다.

* 탐색
+
이 역할을 통해 스토리지 시스템을 추가할 수 있습니다.

* 스토리지 생성
+
이 역할을 사용하여 스토리지를 생성할 수 있습니다. 또한 검색 역할과 연결된 모든 Privileges가 포함됩니다.

* 스토리지를 수정합니다
+
이 역할을 사용하여 스토리지를 수정할 수 있습니다. 또한 검색 및 스토리지 역할과 연결된 모든 Privileges가 포함됩니다.

* 스토리지 폐기
+
이 역할을 사용하면 스토리지를 제거할 수 있습니다. 또한 검색, 스토리지 생성 및 스토리지 역할 수정과 관련된 모든 Privileges도 포함됩니다.





=== 역할이 있는 사용자를 생성합니다

사용자 환경에 대한 구성 옵션을 선택한 후 * 추가 * 를 클릭하면 ONTAP가 사용자 및 역할을 생성합니다. 생성된 역할의 이름은 다음 값을 연결한 것입니다.

* JSON 파일에 정의된 상수 접두사 값(예: "OTV_10")
* 선택한 제품 기능
* 권한 집합 목록입니다.


.예
`OTV_10_VSC_Discovery_Create`

새 사용자가 "사용자 및 역할" 페이지의 목록에 추가됩니다. HTTP 및 ONTAPI 사용자 로그인 방법이 모두 지원됩니다.
