---
sidebar: sidebar 
permalink: automation/first-call.html 
keywords: ontap tools for vmware vsphere rest api reference, first rest api call, acquire access token 
summary: curl을 사용하여 API 호출을 실행하여 VMware vSphere 10 REST API용 ONTAP 툴을 시작할 수 있습니다. 
---
= VMware vSphere 10 REST API 호출용 첫 번째 ONTAP 툴
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
curl을 사용하여 API 호출을 실행하여 VMware vSphere 10 REST API용 ONTAP 툴을 시작할 수 있습니다.



== 시작하기 전에

curl 예제에 필요한 정보와 매개변수를 검토해야 합니다.

.필수 정보입니다
다음이 필요합니다.

* VMware vSphere 10 IP 주소 또는 FQDN 및 포트용 ONTAP 툴
* ONTAP 도구 관리자 자격 증명(사용자 이름 및 암호)


.매개 변수 및 변수
아래에 제시된 컬에는 Bash 스타일 변수가 포함됩니다. 이러한 변수는 Bash 환경에서 설정하거나 명령을 실행하기 전에 수동으로 업데이트할 수 있습니다. 변수를 설정하면 셸이 실행되기 전에 각 명령으로 값을 대체합니다. 변수는 아래 표에 설명되어 있습니다.

[cols="25,75"]
|===
| 변수 | 설명 


| $FQDN_IP_port | 포트 번호와 함께 ONTAP 도구 관리자의 정규화된 도메인 이름 또는 IP 주소입니다. 


| $MYUSER | ONTAP 도구 관리자 계정의 사용자 이름입니다. 


| $MYPASSWORD | ONTAP 도구 관리자 사용자 이름과 연결된 암호입니다. 


| $access_token입니다 | ONTAP 도구 관리자가 발급한 액세스 토큰. 
|===
Linux CLI에서의 다음 명령 및 출력은 변수를 설정하고 표시하는 방법을 보여줍니다.

[listing]
----
FQDN_IP_PORT=172.14.31.224:8443
echo $FQDN_IP
172.14.31.224:8443
----


== 1단계: 액세스 토큰을 획득합니다

REST API를 사용하려면 액세스 토큰을 얻어야 합니다. 액세스 토큰을 요청하는 방법의 예는 다음과 같습니다. 환경에 적합한 값으로 대체해야 합니다.

[source, curl]
----
curl --request POST \
--location "https://$FQDN_IP_PORT/virtualization/api/v1/auth/login” \
--header "Content-Type: application/json" \
--header "Accept: */*" \
-d "{"username": "$MYUSER", "password": "$MYPASSWORD"}"
----
응답에 제공된 액세스 토큰을 복사하고 저장합니다.



== 2단계: REST API 호출을 실행합니다

액세스 토큰이 있으면 curl을 사용하여 REST API 호출을 실행할 수 있습니다. 첫 번째 단계에서 획득한 액세스 토큰을 포함합니다.

.컬의 예
[source, curl]
----
curl --request GET \
--location "https://$FQDN_IP_PORT/virtualization/api/v1/vcenters" \
--header "Accept: */*" \
--header "x-auth: $ACCESS_TOKEN"
----
JSON 응답에는 ONTAP Tools Manager에 구성된 VMware vCenter 인스턴스 목록이 포함됩니다.
