---
permalink: automation/rest-implementation.html 
sidebar: sidebar 
keywords: ontap tools vmware vsphere rest api reference 
summary: REST에서 일반적인 기술 세트와 모범 사례를 설정하지만 각 API의 정확한 구현은 설계 선택에 따라 다를 수 있습니다. 그리고 VMware vSphere 10 REST API용 ONTAP 툴의 설계 방법을 숙지한 후에 사용해야 합니다. 
---
= VMware vSphere 10 REST API용 ONTAP 툴 구현 세부 정보입니다
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
REST에서 일반적인 기술 세트와 모범 사례를 설정하지만 각 API의 정확한 구현은 설계 선택에 따라 다를 수 있습니다. 그리고 VMware vSphere 10 REST API용 ONTAP 툴의 설계 방법을 숙지한 후에 사용해야 합니다.

REST API에는 vCenter 및 Aggregate와 같은 몇 가지 리소스 범주가 포함되어 있습니다. 자세한 내용은 를 link:../automation/api-reference.html["API 참조"]참조하십시오.



== REST API 액세스 방법

ONTAP 툴 로드 밸런서 IP 주소와 포트를 통해 VMware vSphere 10 REST API용 ONTAP 툴에 액세스할 수 있습니다. 전체 URL에는 다음과 같은 여러 부분이 있습니다.

* ONTAP 도구 IP 주소 및 포트
* API 버전
* 자원 범주
* 특정 리소스


초기 구성 중에 IP 주소를 구성해야 하며 포트는 항상 8443입니다. 또한 VMware vSphere 10용 특정 ONTAP 툴의 경우 URL의 첫 번째 부분은 일정합니다. 끝점마다 자원 범주와 특정 자원만 다릅니다.


CAUTION: 아래 예제의 IP 주소 및 포트 값은 예시용입니다. 환경에 맞게 이러한 값을 변경해야 합니다.

.인증 서비스 액세스 예
`\https://10.61.25.34:8443/virtualization/api/v1/auth/login`

이 URL은 POST 메서드를 사용하여 액세스 토큰을 요청하는 데 사용할 수 있습니다.

.vCenter Server를 나열하는 예입니다
`\https://10.61.25.34:8443/virtualization/api/v1/vcenters`

이 URL은 Get 메서드를 사용하여 정의된 vCenter Server 인스턴스의 목록을 요청하는 데 사용할 수 있습니다.



== HTTP 세부 정보입니다

VMware vSphere 10 REST API용 ONTAP 툴은 HTTP 및 관련 매개 변수를 사용하여 리소스 인스턴스 및 컬렉션에 대해 작동합니다. HTTP 구현에 대한 자세한 내용은 아래에 나와 있습니다.



=== HTTP 메서드

REST API가 지원하는 HTTP 메서드 또는 동사는 아래 표에 나와 있습니다.

[cols="15,15,70"]
|===
| 방법 | CRUD | 설명 


| 가져오기 | 읽기 | 리소스 인스턴스 또는 컬렉션의 개체 속성을 검색합니다. 이 작업은 컬렉션과 함께 사용할 때 목록 작업으로 간주됩니다. 


| 게시 | 생성 | 입력 매개 변수를 기반으로 새 리소스 인스턴스를 만듭니다. 


| 를 누릅니다 | 업데이트 | 제공된 JSON 요청 본문으로 전체 리소스 인스턴스를 업데이트합니다. 사용자가 수정할 수 없는 키 값은 유지됩니다. 


| 패치 | 업데이트 | 요청에 대해 선택한 변경 사항을 리소스 인스턴스에 적용하도록 요청합니다. 


| 삭제 | 삭제 | 기존 리소스 인스턴스를 삭제합니다. 
|===


=== 요청 및 응답 헤더

다음 표에는 REST API와 함께 사용되는 가장 중요한 HTTP 헤더가 요약되어 있습니다.

[cols="30,15,55"]
|===
| 머리글 | 유형 | 사용 참고 사항 


| 수락 | 요청하십시오 | 클라이언트 응용 프로그램에서 허용할 수 있는 콘텐츠 유형입니다. 유효한 값에는 '\ */ * ' OR `application/json`이 포함됩니다. 


| X - 인증 | 요청하십시오 | 클라이언트 응용 프로그램을 통해 요청을 실행하는 사용자를 식별하는 액세스 토큰이 포함되어 있습니다. 


| Content-Type(콘텐츠 유형) | 응답 | 요청 헤더에 따라 서버에서 `Accept` 반환됩니다. 
|===


=== HTTP 상태 코드입니다

REST API에서 사용하는 HTTP 상태 코드는 다음과 같다.

[cols="15,20,65"]
|===
| 코드 | 의미 | 설명 


| 200 | 좋습니다 | 새 리소스 인스턴스를 만들지 않는 호출의 성공 여부를 나타냅니다. 


| 201 | 작성됨 | 리소스 인스턴스에 대한 고유 식별자를 사용하여 개체가 생성되었습니다. 


| 202 | 수락됨 | 요청이 수락되었으며 요청을 수행하기 위한 백그라운드 작업이 생성되었습니다. 


| 204 | 콘텐츠가 없습니다 | 반환된 콘텐츠가 없지만 요청이 성공했습니다. 


| 400 | 잘못된 요청입니다 | 요청 입력이 인식되지 않거나 부적절합니다. 


| 401 | 권한이 없습니다 | 사용자에게 권한이 없으므로 인증을 받아야 합니다. 


| 403 | 금지됨 | 인증 오류로 인해 액세스가 거부되었습니다. 


| 404 | 찾을 수 없습니다 | 요청에서 참조되는 리소스가 없습니다. 


| 409 | 충돌 | 개체가 이미 있으므로 개체를 만들지 못했습니다. 


| 500 | 내부 오류입니다 | 서버에서 일반적인 내부 오류가 발생했습니다. 
|===


== 인증

REST API에 대한 클라이언트 인증은 액세스 토큰을 사용하여 수행됩니다. 토큰 및 인증 프로세스의 관련 특징은 다음과 같습니다.

* 클라이언트는 ONTAP 도구 관리자 관리자 자격 증명(사용자 이름 및 암호)을 사용하여 토큰을 요청해야 합니다.
* 토큰은 JSON 웹 토큰(JWT)으로 포맷됩니다.
* 각 토큰은 60분 후에 만료됩니다.
* 클라이언트의 API 요청은 요청 헤더에 토큰을 포함해야 `x-auth` 합니다.


액세스 토큰을 요청하고 사용하는 예는 을 link:../automation/first-call.html["첫 번째 REST API 호출"]참조하십시오.



== 동기 및 비동기 요청

대부분의 REST API 호출은 빠르게 완료되므로 동기식으로 실행됩니다. 즉, 요청이 완료된 후 상태 코드(예: 200)를 반환합니다. 백그라운드 작업을 사용하여 비동기적으로 실행하는 데 시간이 오래 걸리는 요청

비동기적으로 실행되는 API 호출을 실행한 후 서버는 202 HTTP 상태 코드를 반환합니다. 이는 요청이 수락되었지만 아직 완료되지 않았음을 나타냅니다. 백그라운드 작업을 쿼리하여 성공 또는 실패를 포함하여 상태를 확인할 수 있습니다.

비동기식 처리는 데이터 저장소 및 VVOL 작업을 포함하여 여러 유형의 장기 실행 작업에 사용됩니다. 자세한 내용은 Swagger 페이지에서 REST API의 작업 관리자 범주를 참조하십시오.
