---
permalink: configure/add-storage-backend.html 
sidebar: sidebar 
keywords:  
summary: 스토리지 백엔드는 ESXi 호스트가 데이터 스토리지에 사용하는 시스템입니다. 
---
= 스토리지 백엔드를 추가합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 백엔드를 추가하면 ONTAP 클러스터를 온보딩할 수 있습니다.

* 이 작업에 대한 정보 *

멀티 테넌트 아키텍처의 전역 범위 클러스터에 스토리지 백엔드를 추가하려면 ONTAP Tools Manager를 사용하여 스토리지 백엔드를 추가합니다. 글로벌 클러스터에 스토리지 백엔드를 추가한 후에는 클러스터를 원하는 vCenter 테넌트와 연결해야 합니다. vCenter 테넌트가 원하는 SVM(Storage Virtual Machine)을 온보딩해야 합니다. 이를 통해 SVM 사용자는 VVOL 데이터 저장소를 프로비저닝할 수 있습니다. SVM을 사용하여 vCenter에서 스토리지를 추가할 수 있습니다.

로컬 범위 클러스터에 스토리지 백엔드를 추가하려면 vCenter 서버에서 ONTAP 툴 플러그인을 사용하여 ONTAP 시스템을 직접 추가합니다.

[role="tabbed-block"]
====
.ONTAP 도구 관리자 사용
--

NOTE: 멀티 테넌트 설정에서 스토리지 백엔드 클러스터를 글로벌 및 SVM을 로컬에서 추가하여 SVM 사용자 자격 증명을 사용할 수 있습니다.

.단계
. 웹 브라우저에서 ONTAP 도구 관리자를 실행합니다. `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 구축 중에 제공한 VMware vSphere 관리자 자격 증명용 ONTAP 툴을 사용하여 로그인합니다.
. 측면 표시줄에서 * Storage Backend * 를 선택합니다.
. 스토리지 백엔드를 추가하고 서버 IP 주소 또는 FQDN, 사용자 이름 및 암호 세부 정보를 제공합니다.
+

NOTE: IPv4 및 IPv6 주소 관리 LIF가 지원됩니다.



--
.vSphere Client 사용자 인터페이스 사용
--

NOTE: vSphere Client 사용자 인터페이스를 사용하여 스토리지 백엔드를 추가할 경우 VVol 데이터 저장소에서 SVM 사용자를 직접 추가할 수 없습니다.

. vSphere Client에 로그인합니다
. 바로 가기 페이지의 플러그인 섹션에서 * NetApp ONTAP tools * 를 선택합니다.
. 측면 표시줄에서 * Storage Backend * 를 선택합니다.
. 스토리지 백엔드를 추가하고 서버 IP 주소, 사용자 이름, 암호 및 포트 세부 정보를 제공합니다.
+

NOTE: SVM 사용자를 직접 추가하기 위해 클러스터 기반 자격 증명, IPv4 및 IPv6 주소 관리 LIF를 추가하거나 SVM 관리 LIF에 SVM 기반 자격 증명을 제공할 수 있습니다.



.다음 단계
목록이 새로 고쳐지고 목록에서 새로 추가된 스토리지 백엔드를 볼 수 있습니다.

--
====