---
permalink: configure/configure-esx-server-multipath-and-timeout-settings.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere용 ONTAP 툴은 NetApp 스토리지 시스템에 가장 적합한 ESXi 호스트 다중 경로 설정과 HBA 시간 초과 설정을 확인하고 설정합니다. 
---
= ESXi 호스트 설정을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ESXi 서버 다중 경로 및 시간 초과 설정을 구성하면 운영 경로에 장애가 발생할 경우 백업 스토리지 경로로 원활하게 전환할 수 있으므로 고가용성 및 데이터 무결성을 보장할 수 있습니다.



== ESXi 서버 다중 경로 및 시간 초과 설정을 구성합니다

VMware vSphere용 ONTAP 툴은 ESXi 호스트 다중 경로 설정과 NetApp 스토리지 시스템에 가장 적합한 HBA 시간 초과 설정을 확인하고 설정합니다.

* 이 작업에 대한 정보 *

구성 및 시스템 로드에 따라 이 프로세스에는 시간이 오래 걸릴 수 있습니다. 작업 진행률이 Recent Tasks(최근 작업) 패널에 표시됩니다.

.단계
. VMware vSphere Web Client 홈 페이지에서 * 호스트 및 클러스터 * 를 선택합니다.
. 호스트를 마우스 오른쪽 버튼으로 클릭하고 * NetApp ONTAP tools * > * Update host data * 를 선택합니다.
. VMware vSphere Web Client의 바로 가기 페이지에서 플러그인 섹션에서 * NetApp ONTAP tools * 를 선택합니다.
. VMware vSphere용 ONTAP 툴의 개요(대시보드)에서 * ESXi 호스트 규정 준수 * 카드로 이동합니다.
. 권장 설정 적용 * 링크를 선택합니다.
. 권장 호스트 설정 적용 * 창에서 NetApp 권장 설정에 따라 업데이트할 호스트를 선택하고 * 다음 * 을 선택합니다.
+

NOTE: ESXi 호스트를 확장하여 현재 값을 볼 수 있습니다.

. 설정 페이지에서 필요한 권장 값을 선택합니다.
. 요약 창에서 값을 확인하고 * Finish * 를 선택합니다. 최근 작업 패널에서 진행 상황을 추적할 수 있습니다.




== ESXi 호스트 값을 설정합니다

VMware vSphere용 ONTAP 툴을 사용하면 ESXi 호스트에서 시간 초과 및 기타 값을 설정하여 최상의 성능과 성공적인 페일오버를 보장할 수 있습니다. VMware vSphere용 ONTAP 툴 세트는 내부 NetApp 테스트를 기반으로 합니다.

ESXi 호스트에서 다음 값을 설정할 수 있습니다.



=== HBA/CNA 어댑터 설정

다음 매개 변수를 기본값으로 설정합니다.

* Disk.QFullSampleSize 를 참조하십시오
* Disk.QFullThreshold를 참조하십시오
* Emulex FC HBA 시간 초과
* QLogic FC HBA 시간 초과




=== MPIO 설정

MPIO 설정은 NetApp 스토리지 시스템에 대한 기본 경로를 정의합니다. 또한 사용 가능한 경로 중 최적화된 경로를 결정하고(상호 연결 케이블을 통과하는 최적화되지 않은 경로와 비교) 기본 경로를 이러한 경로 중 하나로 설정합니다.

고성능 환경에서 또는 단일 LUN 데이터 저장소를 사용하여 성능을 테스트하는 경우 기본 IOPS 설정인 1000에서 값 1로 라운드 로빈(VMW_PSP_RR) PSP(경로 선택 정책)의 로드 밸런싱 설정을 변경하는 것이 좋습니다.


NOTE: MPIO 설정은 NVMe, NVMe/FC 및 NVMe/TCP 프로토콜에는 적용되지 않습니다.



=== NFS 설정

|===


| 매개 변수 | 이 값을 다음으로 설정... 


| NET.TcpipHeapSize | 32 


| net.TcpipHeapMax | 1024MB 


| NFS.MaxVolumes | 256 


| NFS41.MaxVolumes를 참조하십시오 | 256 


| NFS.MaxQueueDepth입니다 | 128 이상 


| NFS.HeartbeatMaxFailures 를 참조하십시오 | 10 


| NFS.HeartbeatFrequency 를 선택합니다 | 12 


| NFS.HeartbeatTimeout | 5 
|===