---
permalink: configure/protect-cluster.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: VMware vSphere용 ONTAP 툴을 사용하여 호스트 클러스터의 보호를 관리합니다. 
---
= 호스트 클러스터 보호를 사용하여 보호합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 ONTAP 툴은 호스트 클러스터의 보호를 관리합니다. 선택한 SVM에 속하고 클러스터의 하나 이상의 호스트에 마운트된 모든 데이터 저장소는 호스트 클러스터에서 보호됩니다.

.시작하기 전에
다음 필수 구성 요소가 충족되는지 확인합니다.

* 호스트 클러스터에는 하나의 SVM의 데이터 저장소만 있습니다.
* 호스트 클러스터에 마운트된 데이터 저장소는 클러스터 외부의 호스트에 마운트해서는 안 됩니다.
* 호스트 클러스터에 마운트된 모든 데이터 저장소는 iSCSI/FC 프로토콜을 사용하는 VMFS 데이터 저장소여야 합니다. NVMe/FC 및 NVMe/TCP 프로토콜을 사용하는 VVol, NFS 또는 VMFS 데이터 저장소는 지원되지 않습니다.
* 호스트 클러스터에 마운트된 데이터 저장소를 형성하는 FlexVol/LUN이 기존 CG(정합성 보장 그룹)의 일부가 아니어야 합니다.
* 호스트 클러스터에 마운트된 데이터 저장소를 형성하는 FlexVol/LUN이 기존 SnapMirror 관계에 있으면 안 됩니다.
* 호스트 클러스터에는 데이터 저장소가 하나 이상 있어야 합니다.


.단계
. vSphere Client에 로그인합니다
. 호스트 클러스터를 마우스 오른쪽 버튼으로 클릭하고 * NetApp ONTAP tools * > * Protect Cluster * 를 선택합니다.
. 클러스터 보호 창에서 데이터 저장소 유형 및 소스 VM(스토리지 가상 머신) 세부 정보가 자동으로 채워집니다. Datastores 링크를 선택하여 보호된 데이터 저장소를 봅니다.
. 정합성 보장 그룹 이름 * 을 입력합니다.
. 관계 추가 * 를 선택합니다.
. SnapMirror 관계 추가 * 창에서 * 대상 스토리지 VM * 및 * 정책 * 유형을 선택합니다.
+
정책 유형은 Asynchronous 또는 AutomatedFailOverDuplex 일 수 있습니다.

+
SnapMirror 관계를 AutomatedFailOverDuplex 유형 정책으로 추가하는 경우 VMware vSphere용 ONTAP 툴이 구축된 동일한 vCenter에 타겟 스토리지 VM을 스토리지 백엔드로 추가해야 합니다.

+
AutomatedFailOverDuplex 정책 유형에는 균일하고 균일하지 않은 호스트 구성이 있습니다. uniform host configuration * 토글 버튼을 선택하면 호스트 이니시에이터 그룹 구성이 타겟 사이트에 암시적으로 복제됩니다. 자세한 내용은 을 link:../concepts/ontap-tools-concepts-terms.html["주요 개념 및 용어"]참조하십시오.

. 비균일한 호스트 구성을 사용하도록 선택한 경우 해당 클러스터 내의 각 호스트에 대한 호스트 액세스(소스/타겟)를 선택합니다.
. 추가 * 를 선택합니다.
. protect cluster * 창에서 생성 작업 중에는 보호된 클러스터를 편집할 수 없습니다. 삭제하고 보호를 다시 추가할 수 있습니다. Modify host cluster protection(호스트 클러스터 보호 수정) 작업 중에는 편집 옵션을 사용할 수 있습니다. 줄임표 메뉴 옵션을 사용하여 관계를 편집하거나 삭제할 수 있습니다.
. protect * 버튼을 선택합니다.
+
vCenter 작업이 작업 ID 세부 정보와 함께 생성되며 진행 상황이 Recent Tasks 패널에 표시됩니다. 이 작업은 비동기 작업이며 사용자 인터페이스는 요청 제출 상태만 표시하고 작업이 완료될 때까지 기다리지 않습니다.

. 보호된 호스트 클러스터를 보려면 * NetApp ONTAP tools * > * 보호 * > * 호스트 클러스터 관계 * 로 이동하십시오.

