---
permalink: release-notes/whats-new.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 10.3, ONTAP tools for VMware vSphere' 
summary: VMware vSphere 10.3용 ONTAP 툴에서 사용할 수 있는 새로운 기능에 대해 알아보십시오. 
---
= VMware vSphere 10.3용 ONTAP 툴의 새로운 기능
:allow-uri-read: 


[role="lead"]
VMware vSphere 10.3용 ONTAP 툴에서 사용할 수 있는 새로운 기능에 대해 알아보십시오.

[cols="30%,70%"]
|===
| 업데이트 | 설명 


 a| 
새로운 플랫폼 및 응용 프로그램 버전 지원
 a| 
VMware vSphere 10.3용 ONTAP 툴은 이제 다음과 같은 플랫폼 및 애플리케이션 버전을 지원합니다.

* ONTAP 9.16.0 이상
* VMware vSphere 8.0 U3
* VMware Live Site Recovery 9.0




 a| 
구현 용이성
 a| 
이제 단일 노드 클러스터에서 최소 요구 사항으로 VMware vSphere 10.3용 ONTAP 툴을 배포한 다음 고가용성(HA) 또는 다중 노드 배포로 업데이트할 수 있습니다.



 a| 
원활한 프로비저닝 및 구성
 a| 
VMware vSphere 10.3용 ONTAP 툴은 Trident와 관련된 종속성을 제거했으며 이제 동적 스토리지 프로비저닝을 사용하여 원활한 프로비저닝 및 구성을 지원합니다.



 a| 
REST API 인증을 위한 보안 강화
 a| 
이제 VMware vSphere 10.3용 ONTAP 툴은 CA 서명 인증서에 ONTAP 툴 REST API 및 사용자 인터페이스를 사용하여 보안을 강화합니다.



 a| 
ASA R2 시스템 지원
 a| 
VMware vSphere 10.3용 ONTAP 툴은 ASA R2 시스템에서 VMFS 데이터 저장소 프로비저닝을 지원하여 SnapMirror 활성 동기화 및 SRA/VMware 라이브 사이트 복구를 통해 VMFS 데이터 저장소를 보호합니다.



 a| 
향상된 관찰 가능성
 a| 
VMware vSphere 10.3용 ONTAP 툴은 VMFS, VVOL 데이터 저장소와 해당 VM에 대한 관측성 메트릭 지원을 확장합니다.

|===