---
permalink: manage/certificate-manage.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere용 ONTAP 툴의 단일 인스턴스를 사용하여 여러 vCenter Server 인스턴스를 관리할 수 있습니다. VMware vSphere용 ONTAP 툴은 VASA Provider에 대한 자체 서명 인증서와 함께 구축됩니다. 이 옵션을 사용하면 VVol 데이터 저장소에 대해 하나의 vCenter Server 인스턴스만 관리할 수 있습니다. 
---
= 인증서를 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
구축 중에 기본적으로 ONTAP 툴 및 VASA Provider에 대해 자체 서명된 인증서가 생성됩니다. ONTAP 도구 관리자 인터페이스를 사용하여 인증서를 갱신하거나 사용자 지정 CA로 업그레이드할 수 있습니다. 다중 vCenter 배포에서는 사용자 지정 CA 인증서가 필수입니다.

.시작하기 전에
* 인증서가 발급된 도메인 이름을 가상 IP 주소에 매핑해야 합니다.
* 도메인 이름에 대해 nslookup 검사를 실행하여 도메인이 원하는 IP 주소로 확인되는지 확인합니다.
* 인증서는 도메인 이름과 부하 분산 장치 IP 주소를 사용하여 만들어야 합니다.



NOTE: 로드 밸런서 IP 주소는 FQDN(정규화된 도메인 이름)에 매핑되어야 합니다. 인증서에는 제목 또는 제목 대체 이름의 로드 밸런서 IP 주소에 매핑된 동일한 FQDN이 포함되어야 합니다.


NOTE: CA에서 서명한 인증서에서 자체 서명된 인증서로 전환할 수 없습니다.

[role="tabbed-block"]
====
.ONTAP 도구 인증서를 업그레이드합니다
--
ONTAP 도구 탭에는 인증서 유형(자체 서명/CA 서명) 및 도메인 이름과 같은 세부 정보가 표시됩니다. 배포 중에는 자체 서명된 인증서가 기본적으로 생성됩니다. 인증서를 갱신하거나 인증서를 CA로 업그레이드할 수 있습니다.

.단계
. 웹 브라우저에서 ONTAP 도구 관리자를 실행합니다. `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 구축 중에 제공한 VMware vSphere 관리자 자격 증명용 ONTAP 툴을 사용하여 로그인합니다.
. 인증서를 갱신하려면 * 인증서 * > * ONTAP tools * > * 갱신 * 을 선택합니다.
+
인증서가 만료되었거나 만료 날짜가 임박한 경우 인증서를 갱신할 수 있습니다. 인증서 유형이 CA 서명일 때 갱신 옵션을 사용할 수 있습니다. 팝업 창에서 서버 인증서, 개인 키, 루트 CA 및 중간 인증서 세부 정보를 제공합니다.

+

NOTE: 인증서가 갱신될 때까지 시스템이 오프라인 상태가 되고 ONTAP 도구 관리자 인터페이스에서 로그아웃됩니다.

. 자체 서명 인증서를 사용자 지정 CA 인증서로 업그레이드하려면 * 인증서 * > * ONTAP tools * > * CA로 업그레이드 * 옵션을 선택합니다.
+
.. 팝업 창에서 서버 인증서, 서버 인증서 개인 키, 루트 CA 인증서 및 중간 인증서 파일을 업로드합니다.
.. 이 인증서를 생성한 도메인 이름을 입력하고 인증서를 업그레이드합니다.
+

NOTE: 업그레이드가 완료될 때까지 시스템이 오프라인 상태가 되고 ONTAP 도구 관리자 인터페이스에서 로그아웃됩니다.





--
.VASA Provider 인증서를 업그레이드합니다
--
VMware vSphere용 ONTAP 툴은 VASA Provider에 대한 자체 서명 인증서와 함께 구축됩니다. 이 옵션을 사용하면 VVol 데이터 저장소에 대해 하나의 vCenter Server 인스턴스만 관리할 수 있습니다. 여러 vCenter Server 인스턴스를 관리하고 이러한 인스턴스에서 VVol 기능을 활성화하려면 자체 서명된 인증서를 사용자 지정 CA 인증서로 변경해야 합니다.

.단계
. 웹 브라우저에서 ONTAP 도구 관리자를 실행합니다. `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 구축 중에 제공한 VMware vSphere 관리자 자격 증명용 ONTAP 툴을 사용하여 로그인합니다.
. 인증서를 갱신하려면 * 인증서 * > * VASA 공급자 * 또는 * ONTAP 툴 * > * 갱신 * 을 선택합니다.
. 인증서 * > * VASA 공급자 * 또는 * ONTAP 툴 * > * CA로 업그레이드 * 를 선택하여 자체 서명된 인증서를 사용자 지정 CA 인증서로 업그레이드합니다.
+
.. 팝업 창에서 서버 인증서, 서버 인증서 개인 키, 루트 CA 인증서 및 중간 인증서 파일을 업로드합니다.
.. 이 인증서를 생성한 도메인 이름을 입력하고 인증서를 업그레이드합니다.
+

NOTE: 업그레이드가 완료될 때까지 시스템이 오프라인 상태가 되고 ONTAP 도구 관리자 인터페이스에서 로그아웃됩니다.





--
====