---
permalink: manage/collect-the-log-files.html 
sidebar: sidebar 
keywords:  
summary: 'VMware vSphere용 ONTAP Tools 그래픽 사용자 인터페이스\(GUI\)에서 사용할 수 있는 옵션을 통해 VMware vSphere용 ONTAP 툴에 대한 로그 파일을 수집할 수 있습니다. 기술 지원 부서에서 문제 해결을 위해 로그 파일을 수집하도록 요청할 수 있습니다.' 
---
= 로그 파일을 수집합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere용 ONTAP 툴에 대한 로그 파일은 ONTAP Tools Manager 사용자 인터페이스에서 사용할 수 있는 옵션을 통해 수집할 수 있습니다. 기술 지원 부서에서 문제 해결을 위해 로그 파일을 수집하도록 요청할 수 있습니다.


NOTE: ONTAP Tools Manager에서 로그를 생성하는 데는 모든 vCenter Server 인스턴스에 대한 모든 로그가 포함됩니다. vCenter 클라이언트 사용자 인터페이스에서 로그를 생성하는 작업은 선택한 vCenter Server에 대해 범위가 지정됩니다.

.단계
. 웹 브라우저에서 ONTAP 도구 관리자를 실행합니다. `\https://<ONTAPtoolsIP>:8443/virtualization/ui/`
. 구축 중에 제공한 VMware vSphere 관리자 자격 증명용 ONTAP 툴을 사용하여 로그인합니다.
. 사이드바에서 * 로그 번들 * 을 선택합니다.
+
이 작업은 몇 분 정도 걸릴 수 있습니다.

. 로그 파일을 생성하려면 * Generate * 를 선택하십시오.
. 로그 번들의 레이블을 입력하고 * Generate * 를 선택합니다.
+
tar.gz 파일을 다운로드하여 기술 지원 부서에 보내십시오.



vCenter 클라이언트 사용자 인터페이스를 사용하여 로그 번들을 생성하려면 다음 단계를 수행하십시오.

.단계
. vSphere Client에 로그인합니다
. vSphere Client 홈 페이지에서 * Support * > * Log bundle * > * Generate * 로 이동합니다.
. 로그 번들 레이블을 제공하고 로그 번들을 생성합니다. 파일이 생성되면 다운로드 옵션을 볼 수 있습니다. 다운로드하는 데 시간이 걸릴 수 있습니다.



NOTE: 생성된 로그 번들은 지난 3일 또는 72시간 내에 생성된 로그 번들을 대체합니다.
