---
permalink: manage/edit-hostcluster-protection.html 
sidebar: sidebar 
keywords: vVols datastore,delete vVol 
summary: 보호된 호스트 클러스터의 SnapMirror 관계를 편집할 수 있습니다. 관계를 추가, 수정 및 삭제할 수 있습니다. 하지만 일관성 그룹 이름을 편집할 수는 없습니다. 
---
= 보호된 호스트 클러스터를 수정합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
수정 보호의 일부로 다음 작업을 수행할 수 있습니다. 동일한 워크플로에서 모든 변경 작업을 수행할 수 있습니다.

* 보호된 클러스터에 새 데이터 저장소 또는 호스트를 추가합니다.
* 보호 설정에 새 SnapMirror 관계를 추가합니다.
* 보호 설정에서 기존 SnapMirror 관계를 삭제합니다.
* 기존 SnapMirror 관계 수정




== 호스트 클러스터 보호를 모니터링합니다

호스트 클러스터 보호 상태를 모니터링하려면 다음 절차를 따르십시오. 보호 상태, SnapMirror 관계, 데이터 저장소 및 해당 SnapMirror 상태와 함께 모든 보호 호스트 클러스터를 모니터링할 수 있습니다.

.단계
. vSphere Client에 로그인합니다
. NetApp ONTAP tools * > * 보호 * > * 호스트 클러스터 관계 * 로 이동합니다.
+
보호 열 아래의 아이콘은 보호 상태를 나타냅니다

. 자세한 내용을 보려면 아이콘 위에 마우스를 올려 놓으십시오.




== 새 데이터 저장소 또는 호스트를 추가합니다

새로 추가된 데이터 저장소나 호스트를 보호하려면 다음 절차를 따르십시오. vCenter 기본 사용자 인터페이스를 사용하여 보호된 클러스터에 새 호스트를 추가하거나 호스트 클러스터에 새 데이터 저장소를 생성할 수 있습니다.

.단계
. vSphere Client에 로그인합니다
. 보호된 클러스터의 속성을 편집하려면 다음 중 하나를 수행합니다
+
.. NetApp ONTAP tools * > * 보호 * > * 호스트 클러스터 관계 * 로 이동한 후 클러스터에 대한 줄임표 메뉴를 선택하고 * 편집 * 또는 을 선택합니다
.. 호스트 클러스터를 마우스 오른쪽 버튼으로 클릭하고 * NetApp ONTAP tools * > * Protect Cluster * 를 선택합니다.


. vCenter 기본 사용자 인터페이스에서 데이터 저장소를 생성한 경우 해당 데이터 저장소가 보호되지 않음으로 표시됩니다. 사용자 인터페이스는 클러스터의 모든 데이터 저장소와 보호 상태를 대화 상자에 표시합니다. 완벽한 보호를 활성화하려면 * 보호 * 버튼을 선택하십시오.
. 새 ESXi 호스트를 추가한 경우 보호 상태가 부분적으로 보호됨 으로 표시됩니다. SnapMirror 설정에서 줄임표 메뉴를 선택하고 * 편집 * 을 선택하여 새로 추가된 ESXi 호스트의 근접성을 설정합니다.
+

NOTE: 비동기식 유형 관계의 경우 3차 사이트의 타겟 SVM을 동일한 ONTAP 툴 인스턴스에 추가할 수 없으므로 편집 작업이 지원되지 않습니다. 그러나 타겟 SVM의 시스템 관리자 또는 CLI를 사용하여 관계 구성을 변경할 수 있습니다.

. 필요한 사항을 변경한 후 * 저장 * 을 선택합니다.
. Protect Cluster * 창에서 변경 사항을 확인할 수 있습니다.


vCenter 작업이 생성되고 * Recent task * 패널에서 진행 상황을 추적할 수 있습니다.



== 새 SnapMirror 관계를 추가합니다

.단계
. vSphere Client에 로그인합니다
. 보호된 클러스터의 속성을 편집하려면 다음 중 하나를 수행합니다
+
.. NetApp ONTAP tools * > * 보호 * > * 호스트 클러스터 관계 * 로 이동한 후 클러스터에 대한 줄임표 메뉴를 선택하고 * 편집 * 또는 을 선택합니다
.. 호스트 클러스터를 마우스 오른쪽 버튼으로 클릭하고 * NetApp ONTAP tools * > * Protect Cluster * 를 선택합니다.


. 관계 추가 * 를 선택합니다.
. 새 관계를 * Asynchronous * 또는 * AutomatedFailOverDuplex * 정책 유형으로 추가합니다.
. protect * 를 선택합니다.
+
Protect Cluster * 창에서 변경 사항을 확인할 수 있습니다.



vCenter 작업이 생성되고 * Recent task * 패널에서 진행 상황을 추적할 수 있습니다.



== 기존 SnapMirror 관계를 삭제합니다

비동기식 SnapMirror 관계를 삭제하려면 VMware vSphere용 ONTAP 툴에 2차 사이트 SVM 또는 클러스터를 스토리지 백엔드로 추가해야 합니다. 모든 SnapMirror 관계를 삭제할 수 없습니다. 관계를 삭제하면 ONTAP 클러스터의 해당 관계도 제거됩니다. AutomatedFailOverDuplex SnapMirror 관계를 삭제하면 대상의 데이터 저장소가 매핑 해제되고 일관성 그룹, LUN, 볼륨 및 igroup이 대상 ONTAP 클러스터에서 제거됩니다.

관계를 삭제하면 보조 사이트에 대한 재검사가 트리거되어 매핑되지 않은 LUN이 호스트에서 활성 경로로 제거됩니다.

.단계
. vSphere Client에 로그인합니다
. 보호된 클러스터의 속성을 편집하려면 다음 중 하나를 수행합니다
+
.. NetApp ONTAP tools * > * 보호 * > * 호스트 클러스터 관계 * 로 이동한 후 클러스터에 대한 줄임표 메뉴를 선택하고 * 편집 * 또는 을 선택합니다
.. 호스트 클러스터를 마우스 오른쪽 버튼으로 클릭하고 * NetApp ONTAP tools * > * Protect Cluster * 를 선택합니다.


. SnapMirror 설정 아래에서 줄임표 메뉴를 선택하고 * 삭제 * 를 선택합니다.


vCenter 작업이 생성되고 * Recent task * 패널에서 진행 상황을 추적할 수 있습니다.



== 기존 SnapMirror 관계 수정

비동기식 SnapMirror 관계를 수정하려면 VMware vSphere용 ONTAP 툴에 2차 사이트 SVM 또는 클러스터를 스토리지 백엔드로 추가해야 합니다. AutomatedFailOverDuplex SnapMirror 관계인 경우 구성이 균일한 경우 호스트 근접성을 수정할 수 있고 구성이 균일하지 않은 경우 호스트 액세스를 수정할 수 있습니다. Asynchronous 및 AutomatedFailOverDuplex 정책 유형은 상호 변경할 수 없습니다. 클러스터에서 새로 검색된 호스트에 대한 근접성 또는 액세스를 설정할 수 있습니다.


NOTE: 기존의 비동기식 SnapMirror 관계는 편집할 수 없습니다.

.단계
. vSphere Client에 로그인합니다
. 보호된 클러스터의 속성을 편집하려면 다음 중 하나를 수행합니다
+
.. NetApp ONTAP tools * > * 보호 * > * 호스트 클러스터 관계 * 로 이동한 후 클러스터에 대한 줄임표 메뉴를 선택하고 * 편집 * 또는 을 선택합니다
.. 호스트 클러스터를 마우스 오른쪽 버튼으로 클릭하고 * NetApp ONTAP tools * > * Protect Cluster * 를 선택합니다.


. AutomatedFailoOverDuplex 정책 유형을 선택한 경우 호스트 근접 또는 호스트 액세스 세부 정보를 추가합니다.
. 보호 * 버튼을 선택합니다.


vCenter 작업이 생성되고 * Recent task * 패널에서 진행 상황을 추적할 수 있습니다.
