---
permalink: manage/enable-backup.html 
sidebar: sidebar 
keywords:  
summary: VMware vSphere 10.3용 ONTAP 툴은 동적 스토리지 프로비저닝을 사용하므로 제로 RPO를 달성할 수 없습니다. 하지만 거의 0에 가까운 RPO를 달성할 수 있습니다. 
---
= 백업을 생성하고 설정을 복구합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VMware vSphere 10.3용 ONTAP 툴은 동적 스토리지 프로비저닝을 사용하므로 제로 RPO를 달성할 수 없습니다. 하지만 거의 0에 가까운 RPO를 달성할 수 있습니다. RPO가 0에 가까우려면 설정 백업을 생성하고 새 가상 시스템에서 복원해야 합니다.



== 백업을 생성하고 백업 파일을 다운로드합니다

.단계
. vCenter Server에서 유지 관리 콘솔을 엽니다.
. 유지보수 사용자로 로그인합니다.
. 를 `4` 입력하여 * 지원 및 진단 * 을 선택합니다.
. Enter 키를 눌러 `3` * 시스템 백업 활성화 * 옵션을 선택합니다.
. HA가 아닌 경우 ONTAP 툴 가상 머신을 구축할 vCenter 자격 증명을 입력합니다.
. 5-60분 사이의 백업 빈도 값을 입력합니다.
. Enter * 를 누릅니다
+
이렇게 하면 백업이 생성되며 정기적으로 가상 머신의 데이터 저장소로 백업을 푸시합니다.

. 백업에 액세스하려면 스토리지 섹션으로 이동하여 가상 머신의 데이터 저장소를 선택합니다
. 파일 * 섹션을 선택합니다.
+
파일 섹션에서 디렉토리를 볼 수 있습니다. 디렉토리 이름은 ONTAP 도구 IP 주소이며, 여기서 점(.)은 _backup_으로 접미사가 붙은 밑줄로 바뀝니다.

. 자세한 백업 정보를 보려면 * Files * > * Download * 에서 backup_info.txt 파일을 다운로드하십시오.




== 복구

설정을 복구하려면 기존 가상 머신의 전원을 끄고 초기 구축에 사용된 OVA를 사용하여 새 가상 머신을 구축합니다.

새 가상 머신에 동일한 ONTAP 툴 IP 주소(로드 밸런서 IP)를 사용해야 하며 서비스 사용, 노드 크기, HA 모드 등의 시스템 구성은 초기 구축과 동일해야 합니다.

백업 파일에서 설정을 복구하려면 다음 단계를 수행하십시오.

. vCenter Server에서 유지 관리 콘솔을 엽니다.
. 유지보수 사용자로 로그인합니다.
. 를 `4` 입력하여 * 지원 및 진단 * 을 선택합니다.
. Enter 키를 `2` 눌러 * 원격 진단 액세스 활성화 * 옵션을 선택하고 진단 액세스에 사용할 새 암호를 만듭니다.
. 다운로드된 디렉토리에서 백업 하나를 선택합니다. 마지막 백업 파일 이름은 _backup_info.txt_file에 기록됩니다.
. 아래 명령을 실행하여 백업을 새 가상 머신에 복사하고 메시지가 표시되면 진단 암호를 입력합니다.
+
[listing]
----
scp <Backup_X.tar.enc> diag@<node_ip>:/home/diag/system_recovery.tar.enc
----
+

NOTE: 명령에 언급된 대상 경로 및 파일 이름(/home/diag/system_recovery.tar.enc)을 변경하지 마십시오.

. 백업 파일이 복사되면 진단 셸에 로그인하고 다음 명령을 실행합니다.
+
[listing]
----
sudo perl /home/maint/scripts/post-deploy-upgrade.pl -recovery
----
+
로그는 _/var/log/post-deploy-upgrade.log_file에 기록됩니다.

. 성공적으로 복구되면 서비스 및 vCenter 객체가 복구됩니다.

