---
permalink: manage/migrate-virtual-machines.html 
sidebar: sidebar 
keywords:  
summary: 기존 가상 머신을 데이터 센터에서 마이그레이션할 때 고려해야 할 몇 가지 사항을 알고 있어야 합니다. 
---
= 가상 머신의 마이그레이션 또는 클론 생성 고려 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 센터에서 기존 가상 머신을 마이그레이션할 때 고려해야 할 몇 가지 사항을 알고 있어야 합니다.



== 보호된 가상 시스템을 마이그레이션합니다

보호된 가상 시스템을 다음으로 마이그레이션할 수 있습니다.

* 다른 ESXi 호스트에서 동일한 VVol 데이터 저장소
* 동일한 ESXi 호스트에서 서로 다른 호환되는 VVol 데이터 저장소
* 다른 ESXi 호스트에서 서로 다른 호환되는 VVol 데이터 저장소


가상 머신이 다른 FlexVol 볼륨으로 마이그레이션되면 해당 메타데이터 파일도 가상 머신 정보로 업데이트됩니다. 가상 머신이 동일한 스토리지이지만 다른 ESXi 호스트로 마이그레이션되면 기본 FlexVol 볼륨 메타데이터 파일이 수정되지 않습니다.



== 보호된 가상 머신의 클론을 생성합니다

보호된 가상 컴퓨터를 다음 컴퓨터에 클론 복제할 수 있습니다.

* 복제 그룹을 사용하는 동일한 FlexVol 볼륨의 동일한 컨테이너입니다
+
동일한 FlexVol 볼륨의 메타데이터 파일이 클론 복제된 가상 머신 세부 정보로 업데이트됩니다.

* 복제 그룹을 사용하는 다른 FlexVol 볼륨의 동일한 컨테이너입니다
+
클론 생성된 가상 머신이 배치되는 FlexVol 볼륨에서는 메타데이터 파일이 클론 생성된 가상 머신 세부 정보로 업데이트됩니다.

* 컨테이너 또는 VVOL 데이터 저장소가 서로 다릅니다
+
클론 생성된 가상 머신이 배치되는 FlexVol 볼륨에서는 메타데이터 파일이 업데이트된 가상 머신 세부 정보를 가져옵니다.



VMware는 현재 VM 템플릿에 복제된 가상 머신을 지원하지 않습니다.

보호된 가상 머신의 클론 복제가 지원됩니다.

자세한 내용은 을 https://docs.vmware.com/en/VMware-Horizon/2103/virtual-desktops/GUID-B5020738-8649-4308-A8B0-70AF80527DF6.html["클론 생성을 위한 가상 머신 생성"] 참조하십시오.



== 가상 머신 스냅샷

현재 메모리가 없는 가상 머신 스냅샷만 지원됩니다. 가상 머신에 메모리가 있는 스냅샷이 있는 경우 가상 머신이 보호 대상으로 고려되지 않습니다.

또한 메모리 스냅샷이 있는 보호되지 않는 가상 머신을 보호할 수 없습니다. 이 릴리즈에서는 가상 머신에 대한 보호를 활성화하기 전에 메모리 스냅샷을 삭제해야 합니다.

ASA R2 스토리지 유형이 있는 Windows VM의 경우 가상 머신의 스냅샷을 생성하면 읽기 전용 스냅샷이 됩니다. VM에 대한 전원 호출 시 VASA Provider는 읽기 전용 스냅샷을 사용하여 LUN을 생성한 다음 IOPS를 사용하도록 설정합니다. 전원 끄기 요청 중에 VASA Provider는 생성된 LUN을 삭제한 다음 IOPS를 비활성화합니다.
